### ISSUE TITLE
update_bam is not working in python3 for some bam files

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/coordinates_conversion#23]
Here's the error message:
```
$ update_bam -a Focc_FINAL.scaffolds-GCA_000697945.4_Focc_3.0_genomic-match.tsv Female_Focc_ICD_FOi5DR.bam
INFO       Reading alignment data from: Focc_FINAL.scaffolds-GCA_000697945.4_Focc_3.0_genomic-match.tsv...
INFO       Alignments: 6282
INFO       Processing bam file: Female_Focc_ICD_FOi5DR.bam...
INFO       Update tag SN and LN....
INFO       Program record identifier TopHat
INFO       Only some alignment sections will be updated! Tags won't be updated!
Traceback (most recent call last):
  File "/app/data/mpoelchau/coordinates_conversion/python3_venv/bin/update_bam", line 9, in <module>
    load_entry_point('coordinates-conversion==0.0.0', 'console_scripts', 'update_bam')()
  File "/app/data/mpoelchau/coordinates_conversion/python3_venv/lib64/python3.5/site-packages/coordinates_conversion/bin/update_bam.py", line 215, in main
    Bam_updater.update(Bam_file)
  File "/app/data/mpoelchau/coordinates_conversion/python3_venv/lib64/python3.5/site-packages/coordinates_conversion/bin/update_bam.py", line 38, in update
    self._update_features()
  File "/app/data/mpoelchau/coordinates_conversion/python3_venv/lib64/python3.5/site-packages/coordinates_conversion/bin/update_bam.py", line 164, in _update_features
    if len(start_next_mapping)!=1:
TypeError: object of type 'filter' has no len()
```

**Comment by mpoelchau** [comment]
Fixed in #24.
